// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Subscribers.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SubscriberResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the SubscriberResponseModel class.
        /// </summary>
        public SubscriberResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubscriberResponseModel class.
        /// </summary>
        public SubscriberResponseModel(string email = default(string), string source = default(string), string partnerId = default(string))
        {
            Email = email;
            Source = source;
            PartnerId = partnerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerId")]
        public string PartnerId { get; set; }

    }
}
