// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Subscribers.Client.AutorestClient
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for SubscribersAPI.
    /// </summary>
    public static partial class SubscribersAPIExtensions
    {
            /// <summary>
            /// Checks service is alive
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static object IsAlive(this ISubscribersAPI operations)
            {
                return operations.IsAliveAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Checks service is alive
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> IsAliveAsync(this ISubscribersAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.IsAliveWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a subscribers.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='source'>
            /// Source from which is created the subscription
            /// </param>
            public static IList<SubscriberResponseModel> GetSubsribers(this ISubscribersAPI operations, string source = default(string))
            {
                return operations.GetSubsribersAsync(source).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a subscribers.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='source'>
            /// Source from which is created the subscription
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<SubscriberResponseModel>> GetSubsribersAsync(this ISubscribersAPI operations, string source = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSubsribersWithHttpMessagesAsync(source, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get a subscriber by email.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='email'>
            /// Email of subscriber
            /// </param>
            /// <param name='source'>
            /// Source from which is created the subscription
            /// </param>
            public static SubscriberResponseModel GetSubsribersByEmail(this ISubscribersAPI operations, string email = default(string), string source = default(string))
            {
                return operations.GetSubsribersByEmailAsync(email, source).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a subscriber by email.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='email'>
            /// Email of subscriber
            /// </param>
            /// <param name='source'>
            /// Source from which is created the subscription
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<SubscriberResponseModel> GetSubsribersByEmailAsync(this ISubscribersAPI operations, string email = default(string), string source = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSubsribersByEmailWithHttpMessagesAsync(email, source, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a subscriber.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriber'>
            /// Subscriber request model
            /// </param>
            public static void CreateAsync(this ISubscribersAPI operations, SubscriberRequestModel subscriber = default(SubscriberRequestModel))
            {
                operations.CreateAsyncAsync(subscriber).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a subscriber.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='subscriber'>
            /// Subscriber request model
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task CreateAsyncAsync(this ISubscribersAPI operations, SubscriberRequestModel subscriber = default(SubscriberRequestModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.CreateAsyncWithHttpMessagesAsync(subscriber, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Delete a subscriber.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='email'>
            /// Email of subscriber
            /// </param>
            /// <param name='source'>
            /// Source from which is created the subscription
            /// </param>
            public static void DeleteAsync(this ISubscribersAPI operations, string email = default(string), string source = default(string))
            {
                operations.DeleteAsyncAsync(email, source).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete a subscriber.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='email'>
            /// Email of subscriber
            /// </param>
            /// <param name='source'>
            /// Source from which is created the subscription
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteAsyncAsync(this ISubscribersAPI operations, string email = default(string), string source = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteAsyncWithHttpMessagesAsync(email, source, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
